sets.exported={
    main="Montante +1",
    sub="Utu Grip",
    ammo="Knobkierrie",
    head="Sulevia's Mask +2",
    body="Pumm. Lorica +2",
    hands="Sulev. Gauntlets +2",
    legs={ name="Agoge Cuisses +2", augments={'Enhances "Warrior\'s Charge" effect',}},
    feet="Pumm. Calligae +2",
    neck={ name="War. Beads +2", augments={'Path: A',}},
    waist="Fotia Belt",
    left_ear="Thrud Earring",
    right_ear="Bladeborn Earring",
    left_ring="Shukuyu Ring",
    right_ring="Niqmaddu Ring",
    back={ name="Cichol's Mantle", augments={'VIT+20','Accuracy+20 Attack+20','VIT+10','Weapon skill damage +10%',}},
}