sets.exported={
    main={ name="Sequence", augments={'Path: A',}},
    sub={ name="Colada", augments={'"Dbl.Atk."+2','DEX+5','Accuracy+16','Attack+24','DMG:+12',}},
    ammo="Ginsen",
    head="Aya. Zucchetto +2",
    body="Ayanmo Corazza +2",
    hands="Adhemar Wrist. +1",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+12','DEX+12','MND+20',}},
    feet="Aya. Gambieras +2",
    neck="Loricate Torque +1",
    waist="Flume Belt +1",
    left_ear="Etiolation Earring",
    right_ear="Odnowa Earring +1",
    left_ring="Defending Ring",
    right_ring="Vertigo Ring",
    back="Moonbeam Cape",
}